name: "ARIAC documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@0.7
        with:
          docs-folder: docs/
          formats: ''
          pip-requirements: requirements.txt
          build-html-command: make html
          insert-header-footer: false
          
